services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db

  db:
    image: mariadb:10.11
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db

  # mailpit:
  #   image: axllent/mailpit:latest
  #   ports:
  #     - "8025:8025"
  #     - "1025:1025"
  #   environment:
  #     - MP_SMTP_AUTH_ACCEPT_ANY=1
  #     - MP_SMTP_AUTH_ALLOW_INSECURE=1

  # adminer:
  #   image: adminer:latest
  #   restart: unless-stopped
  #   ports:
  #     - "8008:8080"

volumes:
  mariadb-data:
